CREATE CONSTRAINT gmuser_id IF NOT EXISTS FOR (n:GMUser) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT gmuser_username IF NOT EXISTS FOR (n:GMUser) REQUIRE n.username IS UNIQUE;
CREATE CONSTRAINT campaign_id IF NOT EXISTS FOR (n:Campaign) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT person_id IF NOT EXISTS FOR (n:Person) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT ort_id IF NOT EXISTS FOR (n:Ort) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT event_id IF NOT EXISTS FOR (n:Event) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT traitdef_id IF NOT EXISTS FOR (n:TraitDef) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT playersession_id IF NOT EXISTS FOR (n:PlayerSession) REQUIRE n.id IS UNIQUE;
