"""Seeds the TraitDef catalog for the built-in 'neotopia' ruleset.

Runs at every backend startup (see app/main.py). Uses a deterministic id
(ruleset:category:name) + MERGE, so it's idempotent — safe to run repeatedly
without duplicating or resetting GM-adjusted per-character ratings, which live
on the separate HAS_TRAIT relationship, not on TraitDef itself.
"""

from app.db.neo4j_driver import get_driver

# Kurze Definitionen fürs Tooltip UND für den KI-Prompt (app/ki/routes.py
# hängt genau diesen Text an den Katalog, damit die KI z.B. weiß, dass
# Feuermagie über "Kräfte" läuft, nicht über "Überleben"). Angelehnt an die
# Fertigkeits-Erklärungen aus dem WoD-Grundregelwerk (docs/reference/Regel
# Details - infotipp optionen.txt), aber auf NeotopiA/Cyberpunk umgeschrieben
# — kein "Magus"-Vokabular, sondern Straße, Konzerne, Chrom, Sprawl.
TRAIT_BESCHREIBUNGEN: dict[str, str] = {
    # --- Attribute Körperlich ---
    "Körperkraft": "Rohe Muskelkraft — heben, tragen, zuschlagen, Türen eintreten.",
    "Geschicklichkeit": "Reflexe, Balance, Feinmotorik — Zielen, Ausweichen, ruhige Hände.",
    "Widerstandsfähigkeit": "Zähigkeit — Schmerzen, Erschöpfung und Schaden wegstecken.",
    # --- Attribute Gesellschaftlich ---
    "Charisma": "Natürliche Ausstrahlung — Sympathie gewinnen, ohne sich anzustrengen.",
    "Manipulation": "Andere gezielt lenken — überreden, täuschen, unter Druck setzen.",
    "Fassung": "Innere Ruhe unter Stress — Nerven behalten, wenn andere durchdrehen.",
    # --- Attribute Geistig ---
    "Intelligenz": "Logik und Wissen anwenden — Probleme lösen, Zusammenhänge erkennen.",
    "Geistesschärfe": "Schnelle Auffassung — Details bemerken, rasch reagieren, im Vorteil bleiben.",
    "Entschlossenheit": "Willenskraft — durchhalten, wenn es hart wird, sich nicht brechen lassen.",
    # --- Fertigkeiten ---
    "Diebeshandwerk": "Schlösser knacken, Taschendiebstahl, Tresore, Sicherheitssysteme umgehen.",
    "Fahren": "Fahrzeuge sicher und unter Druck lenken — Verfolgungsjagden, Manöver.",
    "Handgemenge": "Waffenloser Nahkampf — Schläge, Tritte, Würfe, Klammergriffe.",
    "Handwerk": "Dinge von Hand bauen und reparieren — Mechanik, Elektronik, Werkstoffe.",
    "Heimlichkeit": "Unbemerkt bleiben — sich lautlos bewegen, in Schatten verschmelzen.",
    "Nahkampf": "Kampf mit Waffen — Messer, Stöcke, Klingen, Elektroschocker.",
    "Schusswaffen": "Umgang mit Feuerwaffen — Handhabung, Wartung, Treffsicherheit.",
    "Sportlichkeit": "Körperliche Fitness — Laufen, Klettern, Springen, Balance, Ausdauer.",
    "Überleben": "In Wildnis oder Straße zurechtkommen — Nahrung, Unterschlupf, Fallen, Feuer machen.",
    "Riggen": "Drohnen und Fahrzeuge per Fernsteuerung/Neuralverbindung führen.",
    "Anführen": "Leute zum Mitziehen bringen — Befehle geben, ein Team koordinieren.",
    "Ausflüchte": "Vertrauen gewinnen und ausnutzen — Lügen, Tricksen, Schwindeleien erkennen.",
    "Darbietung": "Auftreten vor Publikum — Musik, Schauspiel, Reden, Performance.",
    "Einschüchtern": "Angst einjagen — Drohgebärde, Präsenz, unterschwellige Gewaltandeutung.",
    "Etiketten": "Gesellschaftliche Umgangsformen — Konzernkreise, High Society, Verhandlungen.",
    "Menschenkenntnis": "Absichten und Lügen anderer durchschauen — Körpersprache, Tonfall lesen.",
    "Szenenkenntnis": "In der Unterwelt zuhause — Straßencodes, Schwarzmarkt, wer wen kennt.",
    "Tierkunde": "Umgang mit Tieren — verstehen, beruhigen, trainieren, versorgen.",
    "Überzeugen": "Andere durch Argumente und Auftreten auf die eigene Seite ziehen.",
    "Maker (Hardware)": "Cyberware, Drohnen und Gadgets bauen, modifizieren, aufrüsten.",
    "Ermitteln": "Spuren finden und verknüpfen — Beweise sichern, Zusammenhänge aufdecken.",
    "Finanzen": "Geldflüsse verstehen — Buchhaltung, Investitionen, Geldwäsche, Märkte lesen.",
    "Geisteswissenschaften": "Geschichte, Sprachen, Kultur, Recht — akademisches Allgemeinwissen.",
    "Medizin": "Wunden versorgen, Diagnosen stellen, medizinische Eingriffe durchführen.",
    "Naturwissenschaften": "Physik, Chemie, Biologie — technische und wissenschaftliche Theorie.",
    "Okkultismus": "Wissen über Magie, Sphären und das Übernatürliche — Theorie, nicht Praxis.",
    "Politik": "Machtstrukturen durchschauen — Konzernpolitik, Straßenpolitik, Bündnisse.",
    "Technologie": "Alltagselektronik bedienen und reparieren — Geräte, einfache Systeme.",
    "Wahrnehmung": "Aufmerksamkeit für Details — etwas bemerken, bevor es zu spät ist.",
    "Matrix": "Sich in der Matrix bewegen — Hacken, Icons lesen, digitale Spuren verfolgen.",
    # --- Hexkraft (Magiewert) ---
    "Hexkraft": "Rohe magische Macht — wie stark und zuverlässig ein Zauber wirkt.",
    # --- Sphären (was die Magie bewirken kann, nicht wie stark) ---
    "Korrespondenz": "Raum und Distanz manipulieren — Fernwahrnehmung, Teleportation, Dinge über Entfernung greifen.",
    "Entropie": "Zufall, Glück/Pech und Verfall lenken — Wahrscheinlichkeiten biegen, Systeme zersetzen, Schwachstellen finden.",
    "Kräfte": "Elementarenergie steuern — Feuer, Elektrizität, Schall, Licht, kinetische Wucht.",
    "Leben": "Lebendiges Gewebe formen — heilen, verwunden, mutieren, den eigenen Körper verändern.",
    "Materie": "Unbelebte Stoffe formen — Metall, Beton, Chemikalien verwandeln, verstärken oder erschaffen.",
    "Gedanken": "Bewusstsein beeinflussen — Gedanken lesen, Illusionen erzeugen, Willen beugen, Erinnerungen verändern.",
    "Ursprung": "Reine Energie an der Quelle anzapfen — Quintessenz ziehen, Dinge aus dem Nichts erschaffen, Auren lesen.",
    "Geister": "Mit der Astralebene und ihren Bewohnern interagieren — dorthin reisen, Geister rufen, binden, verbannen.",
    "Zeit": "Zeit wahrnehmen und verschieben — Vorausschau, Verlangsamung, kurze Sprünge vor oder zurück.",
    # --- NeuroWeaving (Matrix ohne Gerät) ---
    "NeuroWeaving": "Rohe Stärke beim Weben in der Matrix — wie stark und zuverlässig es wirkt.",
    "Brute Force": "Sicherheitssysteme direkt durchbrechen — roh, laut, aber effektiv.",
    "Schleichen": "Unbemerkt durch Systeme bewegen — Spuren verwischen, ICE umgehen.",
    "Daten Verarbeiten": "Große Datenmengen durchsuchen, filtern und auswerten.",
    "Kompilieren": "Eigene Programme/Effekte in Echtzeit zusammenbauen.",
}


TRAIT_LANGBESCHREIBUNGEN: dict[str, str] = {
    # Ausführliche Tooltip-Texte fuer den "Detail"-Knopf im InfoTipp-Popup
    # (siehe frontend/src/regeln/InfoTipp.tsx). Quelle: docs/reference/Master/
    # (Fertigkeiten+Sphaeren) bzw. docs/reference/Neotopia_Attribute_und_
    # Fertigkeiten.md (Attribute+NeuroWeaving) -- der Rohtext lag dort schon
    # lange fertig, war aber nie an die Tooltips angebunden (Mark, 19.09.2026).
    # --- Attribute ---
    'Körperkraft': 'Dieses Attribut misst deine Fähigkeit, schwere Lasten zu bewegen, Türen einzutreten oder mit bloßen Fäusten ernsthaften Schaden anzurichten. Hohe Körperkraft zeigt sich meist durch dichte Muskelmasse, schwere Myomer-Implantate oder einfach rohe, genetisch optimierte Kraft. Auch schlanke Personen können mit illegalen Verstärkungen überraschend stark sein.\n\nStufen:\n• Armselig – Du schaffst kaum mehr als 20 kg.\n•• Durchschnittlich – Normale Alltagskraft (ca. 50 kg).\n••• Gut – Du kannst problemlos 100–120 kg stemmen.\n•••• Außergewöhnlich – 180–200 kg sind für dich machbar.\n••••• Hervorragend – Du bewegst über 250 kg mit relativer Leichtigkeit.\n•••••• Außerhalb menschlicher Norm – Reine Hydraulik oder genetische Monstrosität.',
    'Geschicklichkeit': 'Geschicklichkeit bestimmt, wie flink und präzise du dich bewegst. Es ist entscheidend für Schützen, Einbrecher, Tänzer und alle, die im Nahkampf oder bei heiklen Manövern bestehen müssen. Hohe Werte zeigen sich oft durch Synapsen-Beschleuniger, neuronale Implantate oder jahrelanges Training.\n\nStufen:\n• Armselig – Du stolperst über deine eigenen Füße.\n•• Durchschnittlich – Normale Alltagsbeweglichkeit.\n••• Gut – Du reagierst schnell und sicher.\n•••• Außergewöhnlich – Deine Bewegungen wirken fast animalisch elegant.\n••••• Hervorragend – Katzen wären neidisch.\n•••••• Außerhalb menschlicher Norm – Reflexe jenseits der menschlichen Grenze.',
    'Widerstandsfähigkeit': 'Dieses Attribut zeigt, wie viel dein Körper aushalten kann – ob bei Schussverletzungen, Drogenentzug, Schlafmangel oder toxischer Umgebung. Hohe Widerstandsfähigkeit ist bei Söldnern, Straßenschamanen und Konzern-Security weit verbreitet.\n\nStufen:\n• Armselig – Du wirst schnell krank oder ohnmächtig.\n•• Durchschnittlich – Normale Konstitution.\n••• Gut – Du hältst deutlich mehr aus als die meisten.\n•••• Außergewöhnlich – Du läufst noch, wenn andere schon liegen bleiben.\n••••• Hervorragend – Fast unkaputtbar.\n•••••• Außerhalb menschlicher Norm – Dein Körper weigert sich einfach aufzugeben.',
    'Charisma': 'Charisma misst, wie sehr Leute dich mögen und dir folgen wollen – ohne dass du aktiv manipulieren musst. Es funktioniert sowohl auf der Straße als auch in Konzernkreisen. Hohes Charisma kann durch Biosculpting, Pheromone oder reine Persönlichkeit entstehen.\n\nStufen:\n• Armselig – Die meisten Leute ignorieren dich.\n•• Durchschnittlich – Du wirkst unauffällig sympathisch.\n••• Gut – Leute mögen dich schnell.\n•••• Außergewöhnlich – Du ziehst Aufmerksamkeit an wie ein Neon-Schild.\n••••• Hervorragend – Deine Präsenz ist schwer zu ignorieren.\n•••••• Außerhalb menschlicher Norm – Fast schon charismatische Strahlkraft.',
    'Manipulation': 'Manipulation beschreibt deine Fähigkeit, Menschen durch Worte, Körpersprache oder subtile Druckausübung in eine gewünschte Richtung zu bewegen. Es ist die klassische Fertigkeit von Konzernmanagern, Straßenpolitikern und Betrügern.\n\nStufen:\n• Armselig – Niemand glaubt dir etwas.\n•• Durchschnittlich – Du kannst normal überzeugen.\n••• Gut – Du kannst Leute um den Finger wickeln.\n•••• Außergewöhnlich – Du liest und steuerst Menschen sehr präzise.\n••••• Hervorragend – „Tanzt, meine Puppen.“\n•••••• Außerhalb menschlicher Norm – Fast schon gefährlich überzeugend.',
    'Fassung': 'Fassung zeigt, wie gut du die Nerven behältst, wenn alles um dich herum zusammenbricht. Hohe Fassung ist bei NeuroWeavern, Profikillern und Konzern-Interrogatoren extrem wertvoll.\n\nStufen:\n• Armselig – Du gerätst schnell in Panik.\n•• Durchschnittlich – Normale Belastbarkeit.\n••• Gut – Du behältst meist einen kühlen Kopf.\n•••• Außergewöhnlich – Fast schon unheimlich ruhig.\n••••• Hervorragend – Du wirkst, als wäre nichts je an dir dran.\n•••••• Außerhalb menschlicher Norm – Emotionale Unerschütterlichkeit.',
    'Intelligenz': 'Intelligenz misst deine Fähigkeit, komplexe Zusammenhänge zu erkennen, Daten zu analysieren und kreative Lösungen zu finden. Besonders wichtig für Decker, Wissenschaftler und alle, die mit komplizierten Systemen arbeiten.\n\nStufen:\n• Armselig – Du verstehst die Welt nur oberflächlich.\n•• Durchschnittlich – Normale Intelligenz.\n••• Gut – Du denkst klar und strukturiert.\n•••• Außergewöhnlich – Dein Verstand ist außergewöhnlich scharf.\n••••• Hervorragend – Du denkst mehrere Schritte voraus.\n•••••• Außerhalb menschlicher Norm – Fast schon KI-ähnliche Auffassungsgabe.',
    'Geistesschärfe': 'Geistesschärfe beschreibt, wie schnell du Situationen erfassen und darauf reagieren kannst. Sie ist besonders bei Matrixläufern, Taktikern und allen wichtig, die in Sekundenbruchteilen Entscheidungen treffen müssen.\n\nStufen:\n• Armselig – Du brauchst lange, um zu verstehen, was passiert.\n•• Durchschnittlich – Normale Reaktionszeit.\n••• Gut – Du erkennst Zusammenhänge schnell.\n•••• Außergewöhnlich – Deine Gedanken laufen deutlich schneller als bei den meisten.\n••••• Hervorragend – Fast schon übermenschlich schnelle Auffassung.\n•••••• Außerhalb menschlicher Norm – Dein Geist arbeitet auf einem anderen Level.',
    'Entschlossenheit': 'Entschlossenheit zeigt, wie sehr du an deinen Zielen festhältst, auch wenn alles gegen dich spricht. Hohe Werte findet man bei Fanatikern, Überlebenskünstlern und Menschen, die schon mehrfach tot hätten sein sollen.\n\nStufen:\n• Armselig – Du gibst schnell auf.\n•• Durchschnittlich – Normale Durchhaltefähigkeit.\n••• Gut – Du kannst richtig stur sein.\n•••• Außergewöhnlich – Deine Willenskraft ist beeindruckend.\n••••• Hervorragend – Fast schon fanatisch.\n•••••• Außerhalb menschlicher Norm – Dein Wille bricht nicht.',
    # --- Fertigkeiten ---
    'Diebeshandwerk': 'Diese Fertigkeit umfasst alle klassischen und modernen Techniken des Einbruchs und Diebstahls. Dazu gehören mechanische Schlösser, elektronische Sicherheitssysteme, biometrische Scanner und einfache Alarmanlagen. Wer Diebeshandwerk beherrscht, kann Türen öffnen, die eigentlich verschlossen bleiben sollten – und das möglichst ohne Spuren zu hinterlassen.',
    'Fahren': 'In Neotopia ist Mobilität oft überlebenswichtig. Diese Fertigkeit misst deine Fähigkeit, Fahrzeuge aller Art (Autos, Motorräder, LKWs, Hover-Vehikel) sicher und unter Druck zu führen. Dazu gehört nicht nur normales Fahren, sondern auch riskante Manöver, Verfolgungsjagden, Flucht vor Verfolgern und das Fahren unter schlechten Bedingungen (Schnee, Regen, schlechte Straßen, Matrix-Störungen).\n\nGute Fahrer können in brenzligen Situationen die Kontrolle behalten, während andere schon längst gegen eine Wand oder in einen Abgrund geflogen sind.\n\nStufen:\n• Anfänger: Du kannst ein normales Auto bedienen, solange nichts Unerwartetes passiert.\n•• Unerfahrener Profi: Du bist ein durchschnittlich guter Fahrer und kommst mit den meisten Alltagssituationen zurecht.\n••• Erfahrener Profi: Du kannst auch unter schwierigen Bedingungen sicher fahren und einfache Manöver ausführen.\n•••• Sehr fähiger Profi: Du bist ein sehr guter Fahrer und kannst auch riskante Situationen meistern.\n••••• Weltklasse: Du fährst auf dem Niveau eines professionellen Rennfahrers oder Fluchtspezialisten.\n\nEmpfohlene Spezialitäten:\nVerfolgungsjagden, Fluchtmanöver, Offroad, Schwerlasttransporte, Hover-Fahrzeuge, Nachtfahrten, Aggressive Fahrweise\n\nTypische Träger:\nRunner, Fluchtspezialisten, Konzern-Chauffeure, Schmuggler, ehemalige Rennfahrer, Straßengang-Mitglieder.',
    'Handgemenge': 'In Neotopia enden viele Auseinandersetzungen, bevor überhaupt eine Waffe gezogen wird. Diese Fertigkeit misst deine Fähigkeit, mit bloßen Händen und Füßen Schaden anzurichten und dich zu verteidigen. Es geht um rohe, direkte Gewalt – Schläge, Tritte, Würfe und das gezielte Zufügen von Schmerzen.\n\nGute Anwender dieser Fertigkeit können auch ohne Waffen gefährlich sein und wissen, wie man einen Gegner schnell und effektiv außer Gefecht setzt. In engen Gassen, überfüllten Bars oder bei Überfällen ist das oft die entscheidende Fertigkeit.\n\nStufen:\n• Anfänger: Du kannst dich in einer Prügelei behaupten, wenn du Glück hast.\n•• Unerfahrener Profi: Du weißt, wie man richtig zuschlägt und tritt.\n••• Erfahrener Profi: Wenn die Fäuste fliegen, gehörst du meist zu den Letzten, die noch stehen.\n•••• Sehr fähiger Profi: Selbst erfahrene Kämpfer werden bei dir vorsichtig.\n••••• Weltklasse: Deine Schläge haben oft schon kampfentscheidende Wirkung.\n\nEmpfohlene Spezialitäten:\nSchmutziges Kämpfen, Wirtshausschlägereien, Entwaffnen, Tritte, Würfe, „Friedfertiger Krieger“ (effektiv, aber nicht tödlich)\n\nTypische Träger:\nStraßenkämpfer, ehemalige Soldaten ohne Waffe, Bodyguards, Runner, die oft in Nahkämpfe geraten, Schläger.',
    'Handwerk': 'In Neotopia ist die Fähigkeit, Dinge selbst herzustellen oder zu reparieren, oft überlebenswichtig. Diese Fertigkeit misst dein handwerkliches Können – ob als Mechaniker, Elektroniker, Schmied, Schneider oder Bastler. Du kannst Geräte reparieren, improvisierte Lösungen bauen oder sogar eigene Konstruktionen entwerfen.\n\nViele Runner und Techniker unterschätzen diese Fertigkeit, bis sie plötzlich mitten in der Unterstadt mit einem kaputten Cyberarm oder einem defekten Drohnenantrieb dastehen.\n\nStufen:\n• Anfänger: Du kannst einfache Reparaturen durchführen, wenn du eine Anleitung hast.\n•• Unerfahrener Profi: Du hast solide Grundkenntnisse und kannst die meisten Alltagsgeräte reparieren.\n••• Erfahrener Profi: Du bist schon sehr gut und kannst auch komplexere Probleme lösen.\n•••• Sehr fähiger Profi: Du bist in deinem Handwerk angesehen und kannst auch ungewöhnliche Lösungen finden.\n••••• Weltklasse: Es gibt wenig, was du nicht bauen oder reparieren kannst – selbst unter schwierigen Bedingungen.\n\nEmpfohlene Spezialitäten:\nCyberware-Reparatur, Drohnenbau, Waffenschmied, Elektronik, High-Tech-Basteleien, Improvisierte Konstruktionen, Fahrzeugreparatur\n\nTypische Träger:\nTechniker, Erfinder, Runner mit Bastler-Mentalität, Konzern-Techniker, Straßenmechaniker, alte Runner mit viel Erfahrung.',
    'Heimlichkeit': 'In Neotopia ist es oft überlebenswichtig, nicht gesehen zu werden. Diese Fertigkeit misst deine Fähigkeit, dich lautlos zu bewegen, Schatten zu nutzen und potenzielle Beobachter frühzeitig zu erkennen. Es geht nicht nur um das Verstecken, sondern auch darum, sich in einer Umgebung so zu verhalten, dass man nicht weiter auffällt.\n\nGute Anwender dieser Fertigkeit können sich durch überwachungsschwache Zonen schleichen, Wachen ausweichen oder in einer Menschenmenge untertauchen, ohne Spuren zu hinterlassen.\n\nStufen:\n• Anfänger: Du kannst manchmal im Dunkeln unauffällig sein, wenn du Glück hast.\n•• Unerfahrener Profi: Du bist schon recht gut darin, normaler Beobachtung zu entgehen.\n••• Erfahrener Profi: Du kannst die meisten alltäglichen Überwachungsmaßnahmen umgehen.\n•••• Sehr fähiger Profi: Selbst erfahrene Beobachter haben Mühe, dich zu entdecken.\n••••• Weltklasse: Du bewegst dich wie ein Schatten – selbst in stark überwachten Gebieten.\n\nEmpfohlene Spezialitäten:\nSchatten nutzen, Urbane Tarnung, Geräuschloses Schleichen, Menschenmengen untertauchen, Wachen ausweichen, Spuren verwischen\n\nTypische Träger:\nEinbrecher, Spione, Assassinen, Runner, Diebe, ehemalige Straßenkinder.',
    'Nahkampf': 'In Neotopia enden viele Auseinandersetzungen auf kurze Distanz. Diese Fertigkeit misst deine Fähigkeit, Nahkampfwaffen effektiv einzusetzen – von Messern über Stäbe bis hin zu improvisierten Waffen wie Brecheisen oder Ketten. Es geht um Technik, Timing und die Fähigkeit, auch unter Druck präzise und gefährlich zu bleiben.\n\nGute Anwender dieser Fertigkeit können auch gegen bewaffnete Gegner bestehen und wissen, wie man eine Waffe optimal nutzt, ohne sich selbst zu sehr zu gefährden.\n\nStufen:\n• Anfänger: Du kannst eine einfache Waffe halten, ohne dich sofort selbst zu verletzen.\n•• Unerfahrener Profi: Du kannst eine Waffe in einem echten Kampf einigermaßen effektiv einsetzen.\n••• Erfahrener Profi: Du bist schon recht gut und kannst auch gegen erfahrene Gegner bestehen.\n•••• Sehr fähiger Profi: Du bist ein gefährlicher Nahkämpfer und schüchterst viele Gegner ein.\n••••• Weltklasse: Deine Fähigkeiten mit Nahkampfwaffen sind auf einem extrem hohen Niveau.\n\nEmpfohlene Spezialitäten:\nKlingenwaffen, Stangenwaffen, Improvisierte Waffen, Kettenwaffen, Schnellziehen, Tödliche Präzision\n\nTypische Träger:\nStraßenkämpfer, ehemalige Soldaten, Runner, die Nahkämpfe bevorzugen, Schläger, Assassinen.',
    'Schusswaffen': 'In Neotopia ist die Fähigkeit, mit Feuerwaffen umzugehen, für viele Runner und Bewohner der Unterstadt überlebensnotwendig. Diese Fertigkeit misst dein Wissen über Handhabung, Wartung, Munition und taktischen Einsatz von Schusswaffen – von einfachen Pistolen über Gewehre bis hin zu schweren Waffen.\n\nGute Anwender dieser Fertigkeit wissen nicht nur, wie man trifft, sondern auch, welche Waffe in welcher Situation am besten geeignet ist und wie man sie unter Druck effektiv einsetzt.\n\nStufen:\n• Anfänger: Du kannst eine Waffe bedienen, ohne dich sofort selbst zu gefährden.\n•• Unerfahrener Profi: Du bist mit den gängigsten Waffen vertraut und kannst sie sicher handhaben.\n••• Erfahrener Profi: Du bist ein guter Schütze und kannst auch unter Druck treffen.\n•••• Sehr fähiger Profi: Du bist ein sehr guter Schütze und kannst auch schwierige Situationen meistern.\n••••• Weltklasse: Deine Treffsicherheit und dein taktisches Verständnis sind auf einem extrem hohen Niveau.\n\nEmpfohlene Spezialitäten:\nScharfschützen, Schnellziehen, Drive-by-Schießen, Schwere Waffen, Kybernetische Waffen, Taktische Schießausbildung\n\nTypische Träger:\nRunner, ehemalige Soldaten, Straßengang-Mitglieder, Bodyguards, Assassinen, Scharfschützen.',
    'Sportlichkeit': 'In Neotopia ist es oft von Vorteil, wenn man fit und beweglich ist. Diese Fertigkeit misst deine körperliche Fitness, Ausdauer und allgemeine athletische Fähigkeiten – Laufen, Klettern, Springen, Schwimmen und andere körperliche Aktivitäten. Es geht um die Fähigkeit, den eigenen Körper unter Kontrolle zu haben und auch unter Belastung noch leistungsfähig zu bleiben.\n\nGute Anwender dieser Fertigkeit können auch in schwierigen Situationen körperlich mithalten – sei es bei einer Verfolgungsjagd zu Fuß, beim Klettern über Konzerngebäude oder beim Überleben in der Wildnis.\n\nStufen:\n• Anfänger: Du bist durchschnittlich fit und kannst normale körperliche Belastungen bewältigen.\n•• Unerfahrener Profi: Du trainierst regelmäßig und bist deutlich fitter als der Durchschnitt.\n••• Erfahrener Profi: Du bist sehr fit und kannst auch längere oder intensive Belastungen meistern.\n•••• Sehr fähiger Profi: Du bist auf einem sehr hohen Fitnessniveau und kannst auch schwierige körperliche Herausforderungen annehmen.\n••••• Weltklasse: Deine körperliche Fitness ist auf einem extremen Niveau – selbst erfahrene Athleten sind beeindruckt.\n\nEmpfohlene Spezialitäten:\nParkour, Ausdauersport, Klettern, Schwimmen, Kampfsportkondition, Überlebenstraining\n\nTypische Träger:\nRunner, ehemalige Sportler, Bodyguards, Straßenkämpfer, ehemalige Soldaten.',
    'Überleben': 'In Neotopia ist es manchmal notwendig, ohne die Annehmlichkeiten der Zivilisation auszukommen. Diese Fertigkeit misst deine Fähigkeit, in der Wildnis oder in der urbanen Einöde zu überleben – Nahrung zu finden, Wasser zu beschaffen, Unterschlupf zu bauen und Gefahren zu erkennen und zu vermeiden.\n\nGute Anwender dieser Fertigkeit können auch unter extrem schwierigen Bedingungen überleben und wissen, wie man mit minimalen Mitteln das Beste aus einer Situation macht.\n\nStufen:\n• Anfänger: Du kannst ein paar Tage in der Wildnis überleben, wenn du Glück hast.\n•• Unerfahrener Profi: Du hast bereits einige Erfahrung und kannst dich besser orientieren.\n••• Erfahrener Profi: Du kannst dich in der Wildnis ernähren und grundlegende Fallen stellen.\n•••• Sehr fähiger Profi: Du bist sehr gut darin, auch unter schwierigen Bedingungen zu überleben.\n••••• Weltklasse: Du bist in der Wildnis oder auf der Straße zuhause und kannst auch extrem feindliche Umgebungen meistern.\n\nEmpfohlene Spezialitäten:\nWildnis-Überleben, Urbanes Überleben, Fallenstellen, Nahrungssuche, Wetterbedrohungen, Vorbereitung auf Katastrophen\n\nTypische Träger:\nÜberlebenskünstler, ehemalige Soldaten, Straßenrunner, ehemalige Obdachlose mit langem Überlebenstraining, Mystiker mit Naturbezug.',
    'Riggen': 'In Neotopia ist die Fähigkeit, Drohnen und vernetzte Systeme zu kontrollieren, für viele Runner und Techniker überlebenswichtig. Diese Fertigkeit misst deine Fähigkeit, Drohnen, Fahrzeuge und andere ferngesteuerte Systeme gleichzeitig zu steuern und zu koordinieren – entweder über klassische Fernsteuerung oder über direkte neuronale Schnittstellen (Rigging).\n\nGute Rigger können mehrere Drohnen gleichzeitig im Einsatz haben, schnelle taktische Entscheidungen treffen und ihre Maschinen auch unter extremem Druck effektiv einsetzen. In den Schatten ist ein guter Rigger oft der entscheidende Faktor zwischen Erfolg und katastrophalem Scheitern.\n\nStufen:\n• Anfänger: Du kannst eine einzelne Drohne oder ein einfaches Fahrzeug bedienen.\n•• Unerfahrener Profi: Du kannst mehrere einfache Systeme gleichzeitig steuern und grundlegende Manöver ausführen.\n••• Erfahrener Profi: Du bist ein solider Rigger und kannst auch unter Druck mehrere Drohnen koordinieren.\n•••• Sehr fähiger Profi: Du bist ein sehr guter Rigger und kannst komplexe Operationen mit mehreren Einheiten durchführen.\n••••• Weltklasse: Deine Fähigkeiten als Rigger sind auf einem extrem hohen Niveau – du kannst ganze Schwärme von Drohnen oder komplexe vernetzte Systeme wie ein einziger Organismus steuern.\n\nEmpfohlene Spezialitäten:\nDrohnenschwärme, Fahrzeug-Rigging, Matrix-Rigging, Taktische Koordination, Notfallmanöver, Multi-Tasking\n\nTypische Träger:\nRigger, Technomanten, ehemalige Militärdrohnenpiloten, Runner mit starker technischer Ausrichtung, Konzern-Sicherheitsspezialisten.',
    'Anführen': 'Dieses Talent hilft Ihnen dabei, andere Leute dazu zu bringen, Ihren Vorgaben zu folgen. Sie könnten dies durch Ihre Präsenz, Ihre Sprache oder Ihre Entschlossenheit erreichen oder einfach, weil Sie wissen, was man zum richtigen Zeitpunkt sagen muss. Wenn Sie bellen, springen die Leute — nicht immer vor Begeisterung, aber mit dem widerwilligen Eingeständnis, dass Sie wohl wissen, was zu tun ist (auch wenn das nicht der Fall ist).\n\nStufen:\n• Anfänger: Cheerleader\n\n•• Unerfahrener Profi: Quarterback\n\n••• Erfahrener Profi: Manager\n\n•••• Sehr fähiger Profi: Wirtschaftsboss\n\n••••• Weltklasse: Nick Fury\n\nZu finden bei: Offizieren, Managern, Reportern, Predigern, Lehrern, Teamführern, Kultführern, Bandenbossen, Politikern\n\nEmpfohlene Spezialitäten: Kompetent, Inspirierend, Herrisch, Hart, Tun-oder-Sterben, Mit sanfter Stimme',
    'Ausflüchte': 'In Neotopia ist die Wahrheit oft eine Ware. Diese Fertigkeit misst deine Fähigkeit, soziale Barrieren zu überwinden, Vertrauen zu erzeugen und dieses Vertrauen dann für deine Zwecke zu nutzen. Es geht nicht um rohe Lügen (dafür gibt es Täuschung oder Manipulation), sondern um das geschickte Auslassen von Informationen, das geschickte Andeuten und das Erkennen, wenn jemand dasselbe bei dir versucht.\n\nGute Anwender dieser Fertigkeit können in fast jede Gesellschaftsschicht eindringen – vom Konzern-Vorstand bis zum Straßen-Gang – und dabei meistens unerkannt bleiben. Sie wissen, wann sie charmant, wann sie harmlos und wann sie gefährlich wirken müssen.\n\nStufen:\n• Anfänger: Du kannst manchmal ein unschuldiges Gesicht aufsetzen.\n•• Unerfahrener Profi: Du bist ein kleiner Trickser, der meistens damit durchkommt.\n••• Erfahrener Profi: Du kannst selbst gebildete Leute eine Weile an der Nase herumführen.\n•••• Sehr fähiger Profi: Du bewegst dich fast wie ein Profi zwischen verschiedenen Welten.\n••••• Weltklasse: Selbst erfahrene Konter-Spione und Fixer haben Mühe, deine wahren Absichten zu durchschauen.\n\nEmpfohlene Spezialitäten:\nVorgetäuschte Unschuld, Sexuelle Manipulation, Politisches Taktieren, Betrug erkennen, Untergrund-Kontakte knüpfen, „Ich bin doch nur der Bote“\n\nTypische Träger:\nFixer, Infiltratoren, Konzern-Spione, Hochstapler, charmante Betrüger, erfahrene Runner mit vielen Identitäten.',
    'Darbietung': 'Darbietung deckt alle Formen der öffentlichen Performance ab – Musik, Schauspiel, Reden, Tanzen oder einfach nur charismatisches Auftreten. Besonders wertvoll für Entertainer, Politiker und alle, die Menschen emotional erreichen wollen.',
    'Einschüchtern': 'In Neotopia ist es oft nützlich, wenn andere dich fürchten. Diese Fertigkeit misst deine Fähigkeit, durch Ausstrahlung, Körpersprache oder offene Drohungen andere einzuschüchtern. Es geht nicht um subtile Manipulation, sondern um die direkte Erzeugung von Furcht und Unterwerfung.\n\nGute Anwender dieser Fertigkeit können allein durch ihre Präsenz Räume zum Schweigen bringen oder Gegner dazu bringen, lieber den Schwanz einzuziehen als zu kämpfen. In den Schatten ist das oft effektiver als jede Waffe.\n\nStufen:\n• Anfänger: Du kannst manchmal bedrohlich wirken, wenn du dich anstrengst.\n•• Unerfahrener Profi: Deine Präsenz sorgt dafür, dass die meisten Leute dich ernst nehmen.\n••• Erfahrener Profi: Selbst abgebrühte Typen werden bei dir vorsichtig.\n•••• Sehr fähiger Profi: Deine bloße Anwesenheit erzeugt oft schon Unterwerfung.\n••••• Weltklasse: Allein dein Blick oder deine Stimme reicht oft aus, um Widerstand zu brechen.\n\nEmpfohlene Spezialitäten:\nEiskalter Blick, Brutale Präsenz, „Mit mir oder gegen mich“, Körperliche Einschüchterung, Psychologische Dominanz, Straßenautorität\n\nTypische Träger:\nStraßen-Gang-Bosse, Konzern-Sicherheitschefs, Söldneroffiziere, erfahrene Fixer, charismatische Schläger, alte Runner mit Ruf.',
    'Etiketten': 'Etiketten beschreibt das Wissen um gesellschaftliche Umgangsformen – von Konzern-Empfängen bis hin zu Straßencodes bestimmter Subkulturen. Wer diese Fertigkeit beherrscht, weiß, wie man sich verhält, ohne anzuecken.',
    'Menschenkenntnis': 'In Neotopia ist es lebensgefährlich, nicht zu wissen, was der andere wirklich will. Diese Fertigkeit misst deine Fähigkeit, emotionale Zustände, verborgene Absichten und Lügen zu erkennen. Es geht nicht um logische Analyse von Informationen (dafür gibt es Nachforschungen), sondern um das intuitive Lesen von Körpersprache, Tonfall, Mikroexpressionen und der allgemeinen Ausstrahlung einer Person.\n\nGute Anwender dieser Fertigkeit können oft schon nach wenigen Sätzen einschätzen, ob jemand lügt, unter Druck steht oder etwas verbirgt. In Verhandlungen, Verhören oder beim Umgang mit Fixern und Konzernvertretern ist das oft der entscheidende Vorteil.\n\nStufen:\n• Anfänger: Du spürst manchmal, wenn etwas nicht stimmt.\n•• Unerfahrener Profi: Du erkennst die meisten offensichtlichen Lügen und starken Emotionen.\n••• Erfahrener Profi: Es ist schwer, dich länger zu täuschen.\n•••• Sehr fähiger Profi: Du siehst die wahren Gefühle und Absichten einer Person meist sehr deutlich.\n••••• Weltklasse: Für dich sind die meisten Leute offene Bücher – selbst wenn sie es nicht wollen.\n\nEmpfohlene Spezialitäten:\nLügen erkennen, Emotionen spüren, Körpersprache lesen, Verhöre, Verborgene Absichten, Mikroexpressionen, „Die Maske durchschauen“\n\nTypische Träger:\nFixer, Konzern-Verhandler, erfahrene Runner, Verhöroffiziere, Psychologen, alte Straßenkinder mit gutem Überlebensinstinkt.',
    'Szenenkenntnis': 'In Neotopia ist es oft überlebenswichtig, die Regeln der Straße zu kennen. Diese Fertigkeit misst dein Wissen über die Unterwelt – ihre Codes, Hierarchien, informellen Netzwerke und ungeschriebenen Gesetze. Es geht um das Verständnis, wie man sich in der Schattenwelt bewegt, ohne sofort als Außenseiter erkannt zu werden.\n\nGute Anwender dieser Fertigkeit wissen, wer wen kennt, welche Regeln gelten und wie man sich verhält, um Respekt zu gewinnen oder zumindest nicht sofort angefeindet zu werden.\n\nStufen:\n• Anfänger: Du kennst die grundlegendsten Regeln und Codes der Unterwelt.\n•• Unerfahrener Profi: Du bewegst dich bereits relativ sicher in der Schattenwelt.\n••• Erfahrener Profi: Du kennst die wichtigsten Spielregeln und Netzwerke.\n•••• Sehr fähiger Profi: Du bist in der Unterwelt gut vernetzt und weißt, wie man sich verhält.\n••••• Weltklasse: Du kennst die Unterwelt so gut wie nur wenige – und wirst von vielen respektiert.\n\nEmpfohlene Spezialitäten:\nStraßenpolitik, Bandenstrukturen, Schwarzmarkt-Netzwerke, Informelle Hierarchien, Straßenkultur, Vertrauensnetzwerke\n\nTypische Träger:\nFixer, ehemalige Gang-Mitglieder, Straßenrunner, erfahrene Bewohner der Unterstadt, Journalisten mit Straßenfokus.',
    'Tierkunde': 'In Neotopia gibt es immer noch Tiere – sowohl natürliche als auch genetisch modifizierte oder kybernetisch erweiterte. Diese Fertigkeit misst dein Wissen über Tierverhalten, -pflege, -dressur und den taktischen Einsatz von Tieren. Es geht um das Verständnis, wie Tiere denken, wie man sie beruhigt, trainiert oder in bestimmten Situationen einsetzt.\n\nGute Anwender dieser Fertigkeit können nicht nur mit normalen Tieren umgehen, sondern auch mit den oft unberechenbaren modifizierten oder kybernetischen Kreaturen, die in den Schatten manchmal auftauchen.\n\nStufen:\n• Anfänger: Du kennst die grundlegendsten Verhaltensweisen von gängigen Tieren.\n•• Unerfahrener Profi: Du kannst mit den meisten normalen Tieren umgehen und sie beruhigen.\n••• Erfahrener Profi: Du hast bereits Erfahrung mit dem Training und dem Einsatz von Tieren.\n•••• Sehr fähiger Profi: Du bist sehr gut darin, auch schwierige oder modifizierte Tiere zu handhaben.\n••••• Weltklasse: Deine Fähigkeiten im Umgang mit Tieren sind außergewöhnlich – selbst gefährliche oder stark modifizierte Kreaturen gehorchen dir oft.\n\nEmpfohlene Spezialitäten:\nWilde Tiere, Kybernetische Tiere, Dressur, Tierverhalten in Stresssituationen, Genetisch modifizierte Kreaturen\n\nTypische Träger:\nStraßenschamanen, ehemalige Tiertrainer, Runner mit Tieren als Begleiter, Konzern-Forscher mit Bio-Modifikations-Hintergrund.',
    'Überzeugen': 'In Neotopia ist die Fähigkeit, andere zu überzeugen, oft mächtiger als jede Waffe. Diese Fertigkeit misst deine Fähigkeit, durch logische Argumente, emotionale Appelle oder geschickte Rhetorik andere Menschen dazu zu bringen, deine Sichtweise zu übernehmen oder deine Ziele zu unterstützen. Es geht nicht um Manipulation oder Täuschung (dafür gibt es Ausflüchte), sondern um echte Überzeugungsarbeit.\n\nGute Anwender dieser Fertigkeit können selbst skeptische oder feindlich gesinnte Personen dazu bringen, ihre Position zumindest zu überdenken – und im besten Fall sogar zu unterstützen.\n\nStufen:\n• Anfänger: Du kannst in ruhigen Situationen einfache Argumente vorbringen.\n•• Unerfahrener Profi: Du kannst die meisten Menschen in normalen Gesprächen überzeugen.\n••• Erfahrener Profi: Du bist ein sehr guter Redner und kannst auch schwierige Personen erreichen.\n•••• Sehr fähiger Profi: Deine Überzeugungskraft ist beeindruckend – selbst erfahrene Verhandler werden von dir beeinflusst.\n••••• Weltklasse: Deine rhetorischen Fähigkeiten sind auf einem extrem hohen Niveau – du kannst ganze Gruppen oder sogar Massen bewegen.\n\nEmpfohlene Spezialitäten:\nEmotionale Appelle, Logische Argumentation, Öffentliche Reden, Verhandlungen, Radikale Überzeugung, "Mit sanfter Stimme"\n\nTypische Träger:\nPolitiker, charismatische Fixer, Anführer von Bewegungen, erfahrene Runner, ehemalige Konzern-Manager.',
    'Maker (Hardware)': 'In Neotopia ist die Fähigkeit, eigene Technik zu bauen oder bestehende Geräte stark zu modifizieren, ein großer Vorteil. Diese Fertigkeit misst dein Können im Entwickeln, Bauen und Verbessern von Hardware – von einfachen Gadgets über komplexe Cyberware bis hin zu spezialisierten Drohnen und technischen Systemen.\n\nGute Maker können oft mit begrenzten Mitteln hochfunktionale Ausrüstung herstellen oder bestehende Geräte so stark anpassen, dass sie deutlich leistungsfähiger werden als Serienmodelle.\n\nStufen:\n• Anfänger: Du kannst einfache Geräte bauen und grundlegende Modifikationen vornehmen.\n•• Unerfahrener Profi: Du bist bereits in der Lage, solide Ausrüstung zu bauen und sinnvolle Verbesserungen durchzuführen.\n••• Erfahrener Profi: Du bist ein sehr guter Maker und kannst auch komplexe Systeme entwickeln.\n•••• Sehr fähiger Profi: Deine Fähigkeiten im Bau und der Modifikation von Hardware sind beeindruckend.\n••••• Weltklasse: Du gehörst zu den besten Machern deines Fachs – deine Konstruktionen sind oft einzigartig und hochfunktional.\n\nEmpfohlene Spezialitäten:\nCyberware-Entwicklung, Drohnenbau, Gadget-Design, High-Tech-Basteleien, Improvisierte Technik, Kybernetische Implantate\n\nTypische Träger:\nTechnomanten, Erfinder, Runner mit Bastler-Mentalität, ehemalige Konzern-Techniker, Straßenmechaniker mit Talent.',
    'Ermitteln': 'In Neotopia ist die Fähigkeit, Spuren zu sichern und Zusammenhänge zu erkennen, oft entscheidend. Diese Fertigkeit misst dein Wissen über forensische Methoden, Spurensicherung, Vernehmungstechniken und die logische Verknüpfung von Informationen. Es geht um klassische Ermittlungsarbeit – ob bei der Aufklärung eines Mordes, der Suche nach gestohlenen Daten oder dem Aufdecken von Konzern-Vergehen.\n\nGute Ermittler können auch aus wenigen oder versteckten Spuren weitreichende Schlüsse ziehen und wissen, wie man Beweise sichert, ohne sie zu verderben.\n\nStufen:\n• Anfänger: Du kannst offensichtliche Spuren erkennen und einfache Zusammenhänge herstellen.\n•• Unerfahrener Profi: Du kennst die grundlegenden Ermittlungsmethoden und kannst Beweise sichern.\n••• Erfahrener Profi: Du bist ein sehr guter Ermittler und kannst auch komplexere Fälle bearbeiten.\n•••• Sehr fähiger Profi: Deine Ermittlungsfähigkeiten sind beeindruckend – selbst bei wenigen Spuren findest du oft den richtigen Ansatz.\n••••• Weltklasse: Du gehörst zu den besten Ermittlern – deine Fähigkeit, aus wenigen Hinweisen ein vollständiges Bild zu rekonstruieren, ist außergewöhnlich.\n\nEmpfohlene Spezialitäten:\nForensik, Spurensicherung, Verhöre, Digitale Forensik, Kriminalpsychologie, Straßenermittlung\n\nTypische Träger:\nDetektive, ehemalige Polizisten, Fixer, Runner mit Ermittlungsfokus, Konzern-Sicherheitsleute.',
    'Finanzen': 'In Neotopia ist Geld oft der entscheidende Faktor. Diese Fertigkeit misst dein Wissen über Finanzsysteme, Investitionen, Buchhaltung, Geldwäsche und die wirtschaftlichen Machtstrukturen der Konzerne. Es geht nicht nur um das Verwalten von eigenem Geld, sondern auch um das Verstehen, wie Konzerne und Syndikate ihre Finanzen organisieren und wie man diese Systeme zu seinem Vorteil nutzen kann.\n\nGute Anwender dieser Fertigkeit können oft finanzielle Schwachstellen erkennen, Investitionsmöglichkeiten bewerten oder sogar gezielt finanzielle Angriffe planen.\n\nStufen:\n• Anfänger: Du verstehst die Grundlagen von Geld und einfachen Transaktionen.\n•• Unerfahrener Profi: Du kennst die wichtigsten Finanzinstrumente und kannst einfache Investitionen tätigen.\n••• Erfahrener Profi: Du hast ein gutes Verständnis von Finanzsystemen und kannst komplexere Transaktionen durchführen.\n•••• Sehr fähiger Profi: Deine finanziellen Fähigkeiten sind sehr gut – du kannst auch komplizierte Finanzstrukturen verstehen und nutzen.\n••••• Weltklasse: Du bewegst dich auf dem Niveau eines Finanzexperten und kannst sogar Konzern-Finanzsysteme gezielt beeinflussen.\n\nEmpfohlene Spezialitäten:\nKonzern-Finanzen, Geldwäsche, Investitionen, Kryptowährungen, Schattenwirtschaft, Buchhaltungstricks\n\nTypische Träger:\nFixer, ehemalige Konzern-Finanzmanager, Runner mit wirtschaftlichem Fokus, charismatische Betrüger, Syndikats-Buchhalter.',
    'Geisteswissenschaften': 'In Neotopia ist es oft von Vorteil, die Vergangenheit und die kulturellen Zusammenhänge zu verstehen. Diese Fertigkeit misst dein Wissen über Geschichte, Sprachen, Kultur, Philosophie und gesellschaftliche Entwicklungen. Es geht um die Fähigkeit, historische und kulturelle Kontexte zu erkennen und dieses Wissen in der Gegenwart anzuwenden.\n\nGute Anwender dieser Fertigkeit können oft aus scheinbar unbedeutenden kulturellen oder historischen Hinweisen wichtige Informationen ableiten – sei es bei der Suche nach alten Konzern-Geheimnissen oder beim Umgang mit verschiedenen Subkulturen.\n\nStufen:\n• Anfänger: Du hast eine grundlegende Allgemeinbildung in Geschichte und Kultur.\n•• Unerfahrener Profi: Du kennst die wichtigsten historischen und kulturellen Zusammenhänge.\n••• Erfahrener Profi: Du hast ein breites und fundiertes Wissen in den Geisteswissenschaften.\n•••• Sehr fähiger Profi: Deine Kenntnisse sind sehr umfassend und du kannst auch komplexe kulturelle und historische Zusammenhänge verstehen.\n••••• Weltklasse: Du bewegst dich auf dem Niveau eines echten Experten in den Geisteswissenschaften.\n\nEmpfohlene Spezialitäten:\nAlte Konzern-Geschichte, Urbane Subkulturen, Vergessene Sprachen, Politische Ideengeschichte, Mythologie und urbane Legenden\n\nTypische Träger:\nJournalisten, ehemalige Konzern-Akademiker, Runner mit historischem Interesse, Fixer mit langem Gedächtnis, charismatische Anführer.',
    'Medizin': 'In Neotopia ist es gefährlich, verletzt zu sein. Diese Fertigkeit misst dein Wissen und deine praktischen Fähigkeiten im Umgang mit Verletzungen, Krankheiten und medizinischen Notfällen. Sie reicht von einfacher Erster Hilfe über Wundversorgung bis hin zu chirurgischen Eingriffen und der Behandlung komplexer Zustände.\n\nIn den Schatten ist oft improvisierte Medizin gefragt – mit begrenzten Mitteln, unter Zeitdruck und ohne sterile Bedingungen. Wer hier gut ist, kann Leben retten, wo andere schon aufgegeben haben.\n\nStufen:\n• Anfänger: Du kannst Erste Hilfe leisten und einfache Verletzungen versorgen.\n•• Unerfahrener Profi: Du kannst leichte bis mittelschwere Verletzungen und Krankheiten behandeln.\n••• Erfahrener Profi: Du bist in der Lage, auch schwerwiegende Verletzungen und Krankheiten zu behandeln.\n•••• Sehr fähiger Profi: Du hast fortgeschrittene Kenntnisse in Medizin und Chirurgie.\n••••• Weltklasse: Du bist ein hochangesehener Mediziner und kannst auch unter extrem schwierigen Bedingungen Erfolge erzielen.\n\nEmpfohlene Spezialitäten:\nErste Hilfe, Feldmedizin, Chirurgie, Improvisierte Medizin, Cyberware-Medizin, Gift- und Drogenentzug, Notfallchirurgie\n\nTypische Träger:\nStreetdocs, Runner mit medizinischer Ausbildung, ehemalige Konzern-Ärzte, Sanitäter, erfahrene Überlebenskünstler.',
    'Naturwissenschaften': 'In Neotopia ist wissenschaftliches Verständnis oft der Schlüssel zu technischen und magischen Anwendungen. Diese Fertigkeit misst dein Wissen über Physik, Chemie, Biologie und verwandte Disziplinen. Es geht um das Verständnis der grundlegenden Gesetze der materiellen Welt und wie man sie nutzen oder umgehen kann.\n\nGute Anwender dieser Fertigkeit können oft physikalische oder chemische Zusammenhänge erkennen, die anderen verborgen bleiben – sei es bei der Analyse unbekannter Substanzen, der Vorhersage technischer Effekte oder der Entwicklung neuer Anwendungen.\n\nStufen:\n• Anfänger: Du kennst die grundlegendsten naturwissenschaftlichen Prinzipien.\n•• Unerfahrener Profi: Du hast ein solides Verständnis der wichtigsten naturwissenschaftlichen Disziplinen.\n••• Erfahrener Profi: Dein Wissen ist fundiert und du kannst auch komplexere Zusammenhänge verstehen.\n•••• Sehr fähiger Profi: Du bist ein sehr guter Naturwissenschaftler und kannst auch ungewöhnliche Phänomene analysieren.\n••••• Weltklasse: Dein naturwissenschaftliches Verständnis ist auf einem extrem hohen Niveau.\n\nEmpfohlene Spezialitäten:\nPhysik, Chemie, Biologie, Hyperphysik, Bio-Modifikation, Chemische Kampfstoffe\n\nTypische Träger:\nWissenschaftler, Technomanten, ehemalige Konzern-Forscher, Erfinder, Runner mit wissenschaftlichem Hintergrund.',
    'Okkultismus': 'In Neotopia ist Okkultismus mehr als nur esoterischer Unsinn. Diese Fertigkeit misst dein Wissen über mystische Traditionen, Geheimgesellschaften, verborgene Praktiken und die oft verzerrte Wahrnehmung der magischen Welt durch die breite Öffentlichkeit. Vieles davon ist falsch, unvollständig oder bewusst verfälscht – aber wer die richtigen Quellen kennt, kann echtes Wissen von Blödsinn trennen.\n\nIn einer Welt, in der Magie erst seit rund hundert Jahren wieder öffentlich wirkt, ist dieses Wissen besonders wertvoll, weil viele alte Annahmen und Traditionen neu bewertet werden müssen.\n\nStufen:\n• Anfänger: Du hast von einigen okkulten Themen gehört und kennst die gängigsten Klischees.\n•• Unerfahrener Profi: Du weißt, dass viele populäre Vorstellungen falsch sind und hast erste echte Einblicke.\n••• Erfahrener Profi: Du hast bereits ein respektables Maß an tatsächlichem Wissen angesammelt.\n•••• Sehr fähiger Profi: Dein Wissen ist fundiert und wird von anderen Okkultisten ernst genommen.\n••••• Weltklasse: Du bewegst dich auf dem Niveau eines echten Experten und kennst sowohl die öffentlichen als auch die verborgenen Aspekte.\n\nEmpfohlene Spezialitäten:\nGeheimgesellschaften, Volksmagie, Konzern-Okkultismus, Astrale Phänomene, Historische Traditionen, Moderne Hextech-Magie\n\nTypische Träger:\nMystiker, ehemalige Konzern-Okkultisten, Straßen-Schamanen, Runner mit magischem Fokus, alte Weisen.',
    'Politik': 'In Neotopia ist Politik oft mächtiger als jede Waffe oder jeder Zauber. Diese Fertigkeit misst dein Wissen darüber, wie Macht funktioniert – wer die Fäden zieht, wie Entscheidungen getroffen werden und wie man selbst Einfluss nehmen kann. Es geht um Konzernpolitik, Straßenpolitik, Medieneinfluss und die unsichtbaren Netzwerke, die die Welt tatsächlich regieren.\n\nGute Anwender dieser Fertigkeit wissen, wann ein gut platziertes Wort mehr bewirken kann als ein ganzes Runner-Team – und wann es besser ist, den Mund zu halten.\n\nStufen:\n• Anfänger: Du kennst die grundlegenden Machtverhältnisse in deinem Umfeld.\n•• Unerfahrener Profi: Du verstehst die wichtigsten Spielregeln und weißt, an wen du dich wenden musst.\n••• Erfahrener Profi: Du kannst gezielt Einfluss nehmen und politische Prozesse zu deinem Vorteil nutzen.\n•••• Sehr fähiger Profi: Du bewegst dich sicher zwischen verschiedenen Machtzentren und verstehst die unsichtbaren Verbindungen.\n••••• Weltklasse: Du weißt, wie man die Fäden der Macht zieht – und wann man sie besser in Ruhe lässt.\n\nEmpfohlene Spezialitäten:\nKonzernpolitik, Straßenpolitik, Medieneinfluss, Syndikatsstrukturen, Lobbyarbeit, Machtspiele auf hoher Ebene\n\nTypische Träger:\nFixer, Konzern-Manager, Politiker, erfahrene Runner, Journalisten, charismatische Anführer.',
    'Technologie': 'In Neotopia ist Technologie allgegenwärtig. Diese Fertigkeit misst dein allgemeines Verständnis moderner Geräte und Systeme – von Haushaltsgeräten über Fahrzeuge bis hin zu einfacher Elektronik und grundlegender Technik. Es geht nicht um tiefes Hacking oder komplexe Programmierung (dafür gibt es Computer), sondern um das praktische Bedienen, Warten und einfache Reparieren von Technik des Alltags.\n\nGute Anwender dieser Fertigkeit können auch mit unbekannten Geräten umgehen und improvisierte Lösungen finden, wenn etwas nicht wie geplant funktioniert.\n\nStufen:\n• Anfänger: Du kannst die meisten normalen Geräte bedienen, ohne große Probleme zu bekommen.\n•• Unerfahrener Profi: Du bist mit den gängigsten Technologien vertraut und kannst einfache Reparaturen durchführen.\n••• Erfahrener Profi: Du kannst auch komplexere Geräte bedienen und warten.\n•••• Sehr fähiger Profi: Du bist ein sehr guter Techniker und kannst auch ungewöhnliche Probleme lösen.\n••••• Weltklasse: Deine technischen Fähigkeiten sind auf einem extrem hohen Niveau – du kannst auch hochentwickelte Geräte verstehen und bedienen.\n\nEmpfohlene Spezialitäten:\nFahrzeugtechnik, Elektronik, Medientechnik, Improvisierte Technik, Technomagie, Cyberware-Wartung\n\nTypische Träger:\nTechniker, Runner, ehemalige Konzern-Angestellte, Bastler, Mechaniker.',
    'Wahrnehmung': 'In Neotopia ist es oft überlebenswichtig, seine Umgebung bewusst wahrzunehmen. Diese Fertigkeit misst deine Fähigkeit, Details, Veränderungen und subtile Hinweise in deiner Umgebung zu erkennen – sei es ein verstecktes Mikrofon, eine ungewöhnliche Bewegung in der Menge oder ein schwacher Geruch, der auf Gefahr hinweist.\n\nGute Anwender dieser Fertigkeit bemerken oft Dinge, die anderen entgehen, und können dadurch frühzeitig auf Bedrohungen oder Chancen reagieren.\n\nStufen:\n• Anfänger: Du bemerkst die offensichtlichsten Dinge in deiner Umgebung.\n•• Unerfahrener Profi: Du bist bereits aufmerksamer als die meisten und erkennst viele subtile Hinweise.\n••• Erfahrener Profi: Deine Wahrnehmung ist sehr gut – du bemerkst die meisten relevanten Details.\n•••• Sehr fähiger Profi: Du bist extrem aufmerksam und entgehen dir nur sehr wenige Hinweise.\n••••• Weltklasse: Deine Wahrnehmung ist außergewöhnlich – du bemerkst Dinge, die selbst erfahrene Beobachter übersehen.\n\nEmpfohlene Spezialitäten:\nVisuelle Wahrnehmung, Akustische Wahrnehmung, Geruchssinn, Körperhaltung lesen, Versteckte Objekte finden, Gefahrenspür\n\nTypische Träger:\nRunner, Bodyguards, ehemalige Soldaten, Spione, ehemalige Straßenkinder mit starkem Überlebensinstinkt.',
    'Matrix': 'In Neotopia ist die Matrix allgegenwärtig. Diese Fertigkeit misst deine Fähigkeit, dich in der digitalen Welt zurechtzufinden – Icons zu interpretieren, Sicherheitsmaßnahmen zu erkennen, Spuren zu verfolgen und sich unauffällig zu bewegen. Es geht um das grundlegende Verständnis der Matrix-Architektur und der darin ablaufenden Prozesse.\n\nGute Anwender dieser Fertigkeit können oft schon an der Struktur eines Hosts oder der Art eines Icons erkennen, mit welcher Art von System oder Gegner sie es zu tun haben – lange bevor der eigentliche Hack beginnt.\n\nStufen:\n• Anfänger: Du kannst dich in der Matrix grundlegend bewegen und die wichtigsten Icons erkennen.\n•• Unerfahrener Profi: Du hast ein gutes Verständnis der Matrix-Struktur und kannst die meisten gängigen Sicherheitsmaßnahmen erkennen.\n••• Erfahrener Profi: Du bewegst dich sicher in der Matrix und kannst auch komplexere Systeme einschätzen.\n•••• Sehr fähiger Profi: Deine Matrix-Kenntnisse sind sehr gut – du kannst auch anspruchsvolle Systeme analysieren.\n••••• Weltklasse: Deine Fähigkeit, die Matrix zu lesen und zu verstehen, ist auf einem extrem hohen Niveau.\n\nEmpfohlene Spezialitäten:\nHost-Architektur, Icon-Analyse, Spurenverfolgung, Sicherheitsprotokolle, Matrix-Navigation, Digitale Tarnung\n\nTypische Träger:\nDecker, Technomanten, Runner mit Matrix-Fokus, ehemalige Konzern-Matrix-Spezialisten, Datenarchivare.',
    # --- Sphären ---
    'Korrespondenz': 'Diese Sphäre erlaubt es einem Magier, Entfernungen zu überwinden, Dinge an anderen Orten wahrzunehmen oder Gegenstände über große Distanzen zu beeinflussen. Fortgeschrittene Anwender können sogar Tore zwischen Orten reißen oder mehrere Orte gleichzeitig wahrnehmen.\n\nIn Neotopia ist Korrespondenz besonders wertvoll für Runner, Spione und alle, die Dinge über große Entfernungen bewegen oder beobachten müssen.\n\nStufen:\n• Unmittelbare Raumwahrnehmung:\n  Der Magier kann Dinge in seiner unmittelbaren Umgebung spüren, auch wenn er sie nicht sehen kann.\n\n•• Raum spüren, berühren, verdichten und hindurchgreifen:\n  Der Magier kann seine Sinne über Entfernungen ausstrecken und kleine Gegenstände durch winzige Raumlöcher ziehen.\n\n••• Raum durchstoßen / Tore öffnen oder verschließen:\n  Der Magier kann kleine, temporäre Tore zwischen Orten erschaffen und selbst hindurchtreten.\n\n•••• Raum zerreißen / Bannzeichen / Selbst-Kolokation:\n  Der Magier kann permanente Tore erschaffen, Bereiche isolieren oder an mehreren Orten gleichzeitig erscheinen.\n\n••••• Raumveränderung / Kolokation:\n  Der Magier kann Entfernungen und Dimensionen frei verändern und Orte oder Gegenstände übereinander legen.\n\nEmpfohlene Spezialitäten:\nTeleportation, Fernwahrnehmung, Raumlöcher, Bannzeichen, Multi-Lokation\n\nTypische Träger:\nSpione, ehemalige Konzern-Transporter, Runner mit Fokus auf Mobilität, ehemalige Militär-Teleporter.',
    'Entropie': 'In Neotopia ist nichts von Dauer. Diese Sphäre gibt einem Magier die Macht, die Strömungen von Wahrscheinlichkeit und Verfall zu beeinflussen. Ein Entropie-Kundiger kann Gegnern Pech bringen, Systeme schneller altern lassen, glückliche Zufälle erzwingen oder bestehende Schwächen in Strukturen und Personen gezielt ausnutzen.\n\nIm Gegensatz zu vielen anderen Sphären verursacht Entropie erst ab Rang 4 direkt schweren, schwer heilbaren Schaden. Davor hilft sie vor allem dabei, die Umgebung oder die Wahrscheinlichkeiten gegen einen Gegner zu wenden.\n\nStufen:\n• Gespür für Schwächen, Glück und Verhängnis:\n  Der Magier kann Strömungen der Wahrscheinlichkeit spüren, Schwachstellen in Systemen erkennen und subtile Hinweise deuten, ob jemand lügt oder unter Druck steht.\n\n•• Wahrscheinlichkeit kontrollieren:\n  Der Magier kann jetzt aktiv Einfluss auf zufällige Ereignisse nehmen – Würfel, Karten oder andere scheinbar zufällige Ausgänge leicht in eine gewünschte Richtung lenken.\n\n••• Berechenbare Muster beeinflussen:\n  Der Magier kann die Geschwindigkeit kontrollieren, mit der materielle Objekte versagen oder verfallen. Besonders effektiv bei komplexen Maschinen.\n\n•••• Lebende Dinge beeinflussen:\n  Der Magier kann jetzt direkt Gesundheit oder Verfall in lebende Körper bringen – Segen oder Fluch, plötzliche Krankheit oder erstaunliche Lebenskraft.\n\n••••• Gedanken beeinflussen / Meme formen / Bindender Eid:\n  Der Magier kann Ideen, Überzeugungen und sogar Erinnerungen formen oder zerstören. Ein Eid kann das Schicksal eines Ziels dauerhaft an seine Loyalität binden.\n\nEmpfohlene Spezialitäten:\nSchicksal, Glück, Verfall, Ordnung, Chaos, Nekromantie, Meme, Wahrscheinlichkeitsmanipulation\n\nTypische Träger:\nFatalisten, ehemalige Konzern-Strategen, Straßen-Schamanen, Manipulatoren, alte Weise mit düsterem Humor.',
    'Kräfte': 'Diese Sphäre erlaubt es einem Magier, elementare Energien zu beschwören, zu lenken und zu verwandeln. Feuerbälle, Blitzschläge, Schallwellen, Gravitationsbrunnen oder Lichtmanipulation sind typische Anwendungen. Auf höheren Rängen können große Gebiete beeinflusst werden (Wetter, Feuerstürme, etc.).\n\nIn Neotopia ist Kräfte eine der direktesten und zerstörerischsten Sphären.\n\nStufen:\n• Kräfte wahrnehmen:\n  Der Magier kann elementare Energien spüren (Infrarot, Elektrizität, Schall etc.).\n\n•• Kräfte beeinflussen / Elementare Berührung:\n  Der Magier kann bestehende Energien lenken oder schwache Effekte erzeugen.\n\n••• Geringe Kräfte umwandeln / Telekinese:\n  Der Magier kann Energien verwandeln und telekinetische Effekte wirken.\n\n•••• Mächtige Kräfte kontrollieren / Wetterhexerei:\n  Der Magier kann große Gebiete beeinflussen und mächtige elementare Effekte erzeugen.\n\n••••• Mächtige Kräfte verwandeln / Infernos beschwören:\n  Der Magier kann extrem zerstörerische elementare Phänomene (Tornados, Feuerstürme) hervorrufen.\n\nEmpfohlene Spezialitäten:\nFeuer, Elektrizität, Schall, Licht, Kinetik, Wettermanipulation\n\nTypische Träger:\nKampfmagier, ehemalige Konzern-Sicherheitsspezialisten, Runner mit offensiver Ausrichtung.',
    'Leben': 'Diese Sphäre erlaubt es einem Magier, lebendiges Gewebe zu heilen, zu verletzen, zu mutieren oder radikal zu verändern. Neue Gliedmaßen, biologische Waffen oder die Verwandlung des eigenen Körpers sind typische Anwendungen. Auf höchsten Rängen kann der Magier sogar neue Lebensformen erschaffen.\n\nStufen:\n• Leben spüren:\n  Der Magier kann die Anwesenheit und den Gesundheitszustand naher Lebewesen spüren.\n\n•• Einfache Lebensformen ändern / Selbstheilung:\n  Der Magier kann einfache Organismen verändern und sich selbst heilen.\n\n••• Einfache Lebensformen verwandeln / Selbstveränderung:\n  Der Magier kann radikale Veränderungen an einfachen Organismen vornehmen und sich selbst stark verändern.\n\n•••• Komplexe Lebensformen ändern / Selbstverwandlung:\n  Der Magier kann komplexe Organismen (inklusive Menschen) radikal verändern.\n\n••••• Komplexe Lebensformen verwandeln & erschaffen:\n  Der Magier kann jede gewünschte Lebensform annehmen oder erschaffen.\n\nEmpfohlene Spezialitäten:\nHeilung, Mutation, Gestaltwandel, Biologische Waffen, Selbstverwandlung\n\nTypische Träger:\nBiomancer, ehemalige Konzern-Genetiker, Runner mit starkem Fokus auf Körpermodifikation.',
    'Materie': 'Diese Sphäre erlaubt es einem Magier, alle Arten von unbelebter Materie zu formen, zu verwandeln oder aus Energie zu erschaffen. Metall, Beton, Glas oder komplexe chemische Verbindungen können manipuliert werden. Kombiniert mit anderen Sphären können sogar lebende Materie oder Energie in Materie umgewandelt werden.\n\nStufen:\n• Materiewahrnehmung:\n  Der Magier kann die Eigenschaften und Struktur von Materialien spüren.\n\n•• Einfache Transmutation:\n  Der Magier kann eine Substanz in eine andere verwandeln (ohne Aggregatszustand zu ändern).\n\n••• Materie formen / Komplexe Transmutation:\n  Der Magier kann Materie formen und komplexere Verwandlungen durchführen.\n\n•••• Materie erschaffen / Permanente Veränderung:\n  Der Magier kann Materie aus Energie erschaffen und dauerhafte Veränderungen vornehmen.\n\n••••• Materie vollständig beherrschen:\n  Der Magier hat nahezu vollständige Kontrolle über alle Formen von Materie.\n\nEmpfohlene Spezialitäten:\nMetallurgie, Chemische Verwandlung, Nanotechnologie, Materie-Erschaffung, Strukturelle Manipulation\n\nTypische Träger:\nTechnomanten, ehemalige Konzern-Materialwissenschaftler, Runner mit Fokus auf Ausrüstung.',
    'Gedanken': 'Gedanken erlaubt es, in die Köpfe anderer einzudringen, Illusionen zu erzeugen, Erinnerungen zu verändern oder Willen zu brechen. Fortgeschrittene Anwender können ganze Persönlichkeiten umformen oder kollektive Halluzinationen erzeugen.',
    'Ursprung': 'Diese Sphäre erlaubt es einem Magier, Quintessenz direkt anzuzapfen, Gegenstände mit roher magischer Energie zu erfüllen oder sogar Machtorte zu erschaffen. Auf höheren Rängen kann der Magier Paradoxon beeinflussen und Dinge aus reiner Energie formen.\n\nStufen:\n• Quintessenz spüren:\n  Der Magier kann Quintessenz in Objekten und Lebewesen spüren.\n\n•• Quintessenz kanalisieren:\n  Der Magier kann Quintessenz aus der Umgebung ziehen und in Objekte leiten.\n\n••• Quintessenz formen / Machtorte erschaffen:\n  Der Magier kann Quintessenz formen und Machtorte erschaffen.\n\n•••• Quintessenz beherrschen / Paradoxon beeinflussen:\n  Der Magier hat starke Kontrolle über Quintessenz und kann Paradoxon reduzieren.\n\n••••• Quintessenz vollständig beherrschen:\n  Der Magier kann Quintessenz frei formen und extreme Effekte wirken.\n\nEmpfohlene Spezialitäten:\nQuintessenz-Manipulation, Machtort-Erschaffung, Paradoxon-Kontrolle, Energie-Erschaffung\n\nTypische Träger:\nMystiker, ehemalige Konzern-Okkultisten, Runner mit starkem Fokus auf rohe magische Kraft.',
    'Geister': 'Geister erlaubt es, in die Astralebene zu reisen, Geister zu rufen, zu binden oder zu verbannen. Im Gegensatz zu älteren Traditionen gibt es in Neotopia keine klassische Umbra – nur die Astralebene, die jedoch ähnlich gefährlich und fremdartig ist. Ein Magier kann hier auch Geister in Fetische binden oder sie gegen andere Wesen einsetzen.',
    'Zeit': 'Diese Sphäre erlaubt es einem Magier, Zeit wahrzunehmen, zu verlangsamen oder kurze Sprünge zu machen. Allerdings ist Zeitreisen in Neotopia extrem gefährlich: Da Magie erst seit etwa 100 Jahren wieder existiert, kann ein Zeitreisender leicht in einer Ära stranden, in der es noch keine Magie gab – und dort hilflos zurückgelassen werden. Viele Magier betrachten Zeit daher als eine der gefährlichsten Sphären überhaupt.\n\nStufen:\n• Zeit wahrnehmen:\n  Der Magier kann den Fluss der Zeit spüren und kurze Vorausschau betreiben.\n\n•• Zeit verlangsamen / Beschleunigen:\n  Der Magier kann den Zeitfluss für sich selbst oder andere leicht verändern.\n\n••• Zeitliche Anker setzen / Kurze Sprünge:\n  Der Magier kann kurze Zeitspünge machen oder Ereignisse zeitlich verzögern.\n\n•••• Zeitliche Isolation / Längere Sprünge:\n  Der Magier kann Bereiche zeitlich isolieren oder längere Sprünge wagen (mit hohem Risiko).\n\n••••• Zeitreise / Zeitimmunität:\n  Der Magier kann sich außerhalb der Zeit bewegen oder längere Zeitreisen unternehmen – mit extrem hohem Risiko, in einer Zeit ohne Magie zu stranden.\n\nEmpfohlene Spezialitäten:\nZeitwahrnehmung, Zeitverzerrung, Zeitreise, Zeitliche Isolation, Vorausschau\n\nTypische Träger:\nZeitmagier, ehemalige Konzern-Zeitforscher, Runner mit extremem Risikobewusstsein.\n\nWichtiger Hinweis:\nZeitreisen in Neotopia ist hochgefährlich. Magie existiert erst seit ca. 100 Jahren. Ein Zeitreisender kann leicht in einer prä-magischen Ära stranden.',
    # --- NeuroWeaving ---
    'NeuroWeaving': 'NeuroWeaving ist die Fähigkeit, direkt mit dem eigenen Nervensystem in die Matrix einzudringen und dort zu wirken. Im Gegensatz zum klassischen Decken braucht ein NeuroWeaver kein externes Gerät – sein Gehirn selbst wird zum Interface. Der NeuroWeaving-Wert bestimmt, wie stark und zuverlässig diese Verbindung ist. Hohe Werte bedeuten, dass der Weave tiefer, schneller und gefährlicher wird. Viele NeuroWeaver tragen sichtbare Implantate oder Narben an den Schläfen, wo die direkte Verbindung stattfindet.',
    'Brute Force': 'Brute Force ist die aggressivste Form des NeuroWeaving. Der Weave bricht Sicherheitsprotokolle durch pure Überwältigung – laute, schnelle und oft sehr auffällige Angriffe. Wer diese Fertigkeit nutzt, riskiert schnell ICE-Aufmerksamkeit, hinterlässt aber auch tiefe Spuren im System. Besonders effektiv gegen stark gepanzerte Hosts, aber auch extrem riskant.',
    'Schleichen': 'Schleichen ist die Kunst des stillen Eindringens. Ein NeuroWeaver mit hoher Schleichen-Fertigkeit hinterlässt kaum Spuren, umgeht ICE und kann sich lange Zeit in fremden Systemen aufhalten, ohne entdeckt zu werden. Diese Fertigkeit ist essenziell für Spione, Datendiebe und alle, die lieber unentdeckt bleiben wollen als laute Feuergefechte in der Matrix.',
    'Daten Verarbeiten': 'Daten Verarbeiten erlaubt es dem NeuroWeaver, riesige Datenströme in Echtzeit zu analysieren. Ein erfahrener Weave kann in Sekunden relevante Informationen aus einem Konzernarchiv herausfiltern, versteckte Muster erkennen oder gezielt nach bestimmten Datensätzen suchen. Diese Fertigkeit ist besonders bei Aufträgen gefragt, bei denen es um Informationsbeschaffung geht.',
    'Kompilieren': 'Kompilieren ist die kreative Seite des NeuroWeaving. Der Weave kann in Echtzeit eigene kleine Programme, Werkzeuge oder sogar temporäre Konstrukte erschaffen – von simplen Hilfsroutinen bis hin zu komplexen Angriffs- oder Verteidigungsalgorithmen. Je höher die Fertigkeit, desto mächtiger und stabiler werden diese spontanen Schöpfungen.',
}


# (name, category, defaultMax, sortOrder) — aus Neotopia.xlsx (Charakterblatt-Sheet)
NEOTOPIA_TRAITS: list[tuple[str, str, int, int]] = [
    # Attribute Körperlich (6 Punkte)
    ("Körperkraft", "AttributKörperlich", 6, 1),
    ("Geschicklichkeit", "AttributKörperlich", 6, 2),
    ("Widerstandsfähigkeit", "AttributKörperlich", 6, 3),
    # Attribute Gesellschaftlich
    ("Charisma", "AttributGesellschaftlich", 6, 1),
    ("Manipulation", "AttributGesellschaftlich", 6, 2),
    ("Fassung", "AttributGesellschaftlich", 6, 3),
    # Attribute Geistig
    ("Intelligenz", "AttributGeistig", 6, 1),
    ("Geistesschärfe", "AttributGeistig", 6, 2),
    ("Entschlossenheit", "AttributGeistig", 6, 3),
    # Fertigkeiten (6 Punkte — 20.09.2026 von 5 auf 6 angehoben, damit sie
    # mit dem Attributmaximum gleichzieht, siehe CLAUDE.md)
    ("Diebeshandwerk", "Fertigkeit", 6, 1),
    ("Fahren", "Fertigkeit", 6, 2),
    ("Handgemenge", "Fertigkeit", 6, 3),
    ("Handwerk", "Fertigkeit", 6, 4),
    ("Heimlichkeit", "Fertigkeit", 6, 5),
    ("Nahkampf", "Fertigkeit", 6, 6),
    ("Schusswaffen", "Fertigkeit", 6, 7),
    ("Sportlichkeit", "Fertigkeit", 6, 8),
    ("Überleben", "Fertigkeit", 6, 9),
    ("Riggen", "Fertigkeit", 6, 10),
    ("Anführen", "Fertigkeit", 6, 11),
    ("Ausflüchte", "Fertigkeit", 6, 12),
    ("Darbietung", "Fertigkeit", 6, 13),
    ("Einschüchtern", "Fertigkeit", 6, 14),
    ("Etiketten", "Fertigkeit", 6, 15),
    ("Menschenkenntnis", "Fertigkeit", 6, 16),
    ("Szenenkenntnis", "Fertigkeit", 6, 17),
    ("Tierkunde", "Fertigkeit", 6, 18),
    ("Überzeugen", "Fertigkeit", 6, 19),
    ("Maker (Hardware)", "Fertigkeit", 6, 20),
    ("Ermitteln", "Fertigkeit", 6, 21),
    ("Finanzen", "Fertigkeit", 6, 22),
    ("Geisteswissenschaften", "Fertigkeit", 6, 23),
    ("Medizin", "Fertigkeit", 6, 24),
    ("Naturwissenschaften", "Fertigkeit", 6, 25),
    ("Okkultismus", "Fertigkeit", 6, 26),
    ("Politik", "Fertigkeit", 6, 27),
    ("Technologie", "Fertigkeit", 6, 28),
    ("Wahrnehmung", "Fertigkeit", 6, 29),
    ("Matrix", "Fertigkeit", 6, 30),
    # NeuroWeaving: erst der Wert selbst, dann die vier Fertigkeiten.
    # Aufgebaut wie Hexkraft + Sphären — mit dem Unterschied, dass die
    # Fertigkeiten hier **mitgewürfelt** werden (Regelblatt Zeile 45/96),
    # während Sphären nur beschreiben, was möglich ist.
    ("NeuroWeaving", "NeuroWeavingWert", 10, 1),
    ("Brute Force", "NeuroWeaving", 6, 1),
    ("Schleichen", "NeuroWeaving", 6, 2),
    ("Daten Verarbeiten", "NeuroWeaving", 6, 3),
    ("Kompilieren", "NeuroWeaving", 6, 4),
    # Sphären — bleiben bei 5: feste Stufenbedeutung (1 wahrnehmbar … 5
    # "alles"), eine 6. Stufe wäre inhaltlich unbelegt (Mark, 20.09.2026).
    ("Korrespondenz", "Sphäre", 5, 1),
    ("Entropie", "Sphäre", 5, 2),
    ("Kräfte", "Sphäre", 5, 3),
    ("Leben", "Sphäre", 5, 4),
    ("Materie", "Sphäre", 5, 5),
    ("Gedanken", "Sphäre", 5, 6),
    ("Ursprung", "Sphäre", 5, 7),
    ("Geister", "Sphäre", 5, 8),
    ("Zeit", "Sphäre", 5, 9),
    # Hexkraft ist der Magiewert selbst (nicht zu verwechseln mit den Sphären,
    # die nur beschreiben was möglich ist). Auf dem Blatt eine Reihe von zehn
    # Kästchen, daher Maximum 10 statt 5 wie bei Fähigkeiten. Kostet in der
    # Erstellung 5 Freebees wie ein Attribut.
    ("Hexkraft", "Hexkraft", 10, 1),
]

# Hintergründe stehen **nicht** im Regelwerk — siehe traits/erstellung.py.
# Sie liegen trotzdem im selben Katalog wie alles andere: dadurch erscheinen
# sie ohne Zusatzarbeit auf dem Blatt, lassen sich mit Erfahrung steigern und
# vom Spielleiter überschreiben. Die Liste kommt aus erstellung.py, damit
# Erstellung und Katalog nicht auseinanderlaufen können.
from app.traits.erstellung import HINTERGRUENDE, HINTERGRUND_KATEGORIE, HINTERGRUND_MAX  # noqa: E402

NEOTOPIA_TRAITS += [
    (h["name"], HINTERGRUND_KATEGORIE, HINTERGRUND_MAX, i + 1) for i, h in enumerate(HINTERGRUENDE)
]

# Hintergründe haben ihre Beschreibung schon in HINTERGRUENDE (erstellung.py)
# — hier nachziehen, damit Tooltip/KI-Prompt aus derselben Quelle stammen wie
# der Erstellungs-Assistent, statt den Text ein zweites Mal zu pflegen.
TRAIT_BESCHREIBUNGEN.update({h["name"]: h["beschreibung"] for h in HINTERGRUENDE})


async def seed_traits() -> None:
    driver = get_driver()
    ruleset = "neotopia"
    async with driver.session() as session:
        for name, category, default_max, sort_order in NEOTOPIA_TRAITS:
            trait_id = f"{ruleset}:{category}:{name}"
            await session.run(
                """
                MERGE (t:TraitDef {id: $id})
                SET t.ruleset = $ruleset, t.name = $name, t.category = $category,
                    t.defaultMax = $defaultMax, t.sortOrder = $sortOrder,
                    t.description = $description
                """,
                id=trait_id,
                ruleset=ruleset,
                name=name,
                category=category,
                defaultMax=default_max,
                sortOrder=sort_order,
                description=TRAIT_BESCHREIBUNGEN.get(name, ""),
            )

        await _migriere_arete_zu_hexkraft(session)
        await _seed_trait_erklaerungen(session, ruleset)


async def _seed_trait_erklaerungen(session, ruleset: str) -> None:
    """Befüllt die Erklärungen (Tooltip-Text) aus TRAIT_BESCHREIBUNGEN.

    Ein von der Spielleitung von Hand geschriebener Text (`quelle='HAND'`)
    wird **nie** überschrieben. Ein noch unbearbeiteter KI-Text
    (`quelle='KI'`) darf dagegen aktualisiert werden — so kommen spätere
    Verbesserungen an TRAIT_BESCHREIBUNGEN auch bei bereits gesäten
    Kampagnen an, ohne echte Redaktionsarbeit der SL zu gefährden.

    `langtext`: der ausführliche Text hinter dem "Detail"-Knopf im
    InfoTipp-Popup (TRAIT_LANGBESCHREIBUNGEN) — separat von `text`, weil das
    Popup zuerst nur die Kurzfassung zeigt und die Langfassung erst auf
    Nachfrage nachlädt (Mark, 19.09.2026: die Regelwerk-Texte lagen fix
    fertig in docs/reference/, waren aber nie an die Tooltips angebunden).
    Überschreibt `langtext` nur, solange die Kurzfassung noch nicht von Hand
    bearbeitet wurde — dieselbe HAND/KI-Schutzregel wie beim Kurztext.
    """
    for name, text in TRAIT_BESCHREIBUNGEN.items():
        schluessel = f"trait:{name}"
        langtext = TRAIT_LANGBESCHREIBUNGEN.get(name, "")
        await session.run(
            """
            MERGE (e:Erklaerung {ruleset: $ruleset, schluessel: $schluessel})
            ON CREATE SET e.id = $ruleset + ':' + $schluessel,
                          e.titel = $name, e.text = $text, e.quelle = 'KI',
                          e.langtext = $langtext
            ON MATCH SET e.titel = CASE WHEN e.quelle = 'HAND' THEN e.titel ELSE $name END,
                         e.text = CASE WHEN e.quelle = 'HAND' THEN e.text ELSE $text END,
                         e.langtext = CASE WHEN e.quelle = 'HAND' THEN e.langtext ELSE $langtext END
            """,
            ruleset=ruleset,
            schluessel=schluessel,
            name=name,
            text=text,
            langtext=langtext,
        )


# Alte Kennung aus der Zeit, als der Magiewert "Arete" hiess.
_ALT_ARETE_ID = "neotopia:Arete:Arete"
_HEXKRAFT_ID = "neotopia:Hexkraft:Hexkraft"


async def _migriere_arete_zu_hexkraft(session) -> None:
    """Einmalige Datenkorrektur: aus "Arete" wurde "Hexkraft".

    **Warum es diese Migration überhaupt braucht:** die TraitDef-Kennung ist
    `ruleset:category:name` (siehe oben). Beim Umbenennen im Katalog änderte
    sich damit auch die Kennung — `MERGE` legte also einen *neuen*, leeren
    Knoten `Hexkraft` an, während der alte `Arete`-Knoten mit allen daran
    hängenden Charakterwerten (`HAS_TRAIT`, dort liegt das `rating`) stehen
    blieb. Ergebnis vor dieser Korrektur: das Charakterblatt zeigte die alte
    Arete-Zeile mit den echten Punkten, die Kampfkarte den neuen, leeren
    Hexkraft-Wert — und weil "Arete" für `bogen.sichtbare_kategorien` keine
    Magie-Kategorie mehr ist, sah plötzlich *jeder* Charakter die Zeile.

    Hängt die Werte deshalb auf den Hexkraft-Knoten um und räumt den alten
    weg. Idempotent: nach dem ersten Lauf gibt es keinen Arete-Knoten mehr,
    danach tut sie nichts.

    Ist am Zielwert schon etwas eingetragen (jemand hat nach einem Neustart
    bereits Hexkraft gesetzt), bleibt der neuere Wert stehen — überschrieben
    wird nur eine noch leere 0.
    """
    ergebnis = await session.run(
        """
        MATCH (alt:TraitDef {id: $alt_id})
        MATCH (n)-[h:HAS_TRAIT]->(alt)
        MATCH (neu:TraitDef {id: $neu_id})
        MERGE (n)-[nh:HAS_TRAIT]->(neu)
          ON CREATE SET nh.rating = h.rating, nh.maxOverride = h.maxOverride
          ON MATCH SET nh.rating = CASE WHEN coalesce(nh.rating, 0) = 0 THEN h.rating ELSE nh.rating END
        DELETE h
        RETURN count(*) AS umgehaengt
        """,
        alt_id=_ALT_ARETE_ID,
        neu_id=_HEXKRAFT_ID,
    )
    datensatz = await ergebnis.single()
    umgehaengt = datensatz["umgehaengt"] if datensatz else 0

    # Erst wenn nichts mehr daran hängt — so kann die Migration niemals
    # Charakterwerte mitnehmen, auch wenn oben etwas schiefgegangen wäre.
    await session.run(
        """
        MATCH (alt:TraitDef {id: $alt_id})
        WHERE NOT ()-[:HAS_TRAIT]->(alt)
        DELETE alt
        """,
        alt_id=_ALT_ARETE_ID,
    )
    if umgehaengt:
        print(f"[seed] Arete → Hexkraft: {umgehaengt} Charakterwert(e) umgehängt")
